---
- hosts: all
  become: true
  pre_tasks:

  - name: configure dpkg
    raw: sudo dpkg --configure -a
    ignore_errors: yes
    changed_when: false

  - name: install updates
    tags: always
    apt:
      update_cache: yes
      cache_valid_time: 86400

- hosts: all
  become: true
  tasks:

  - name: collect logs of control nodes
    fetch:
      src: "/var/log/{{ item }}"
      dest: "logs/"
      flat: yes
    with_items:
      - syslog
      - auth.log
